### ISSUE TITLE
Resolvers code readability improvement/question

### ISSUE THREAD

**Issue by adambajguz** [z4kn4fein/stashbox#139]
Hi @z4kn4fein,
I'm wondering why in [ResolutionScope.Resolver.cs](https://github.com/z4kn4fein/stashbox/blob/433c6721e718fda8bfcaaee6aad6de73a3015d9c/src/ResolutionScope.Resolver.cs#L13
) and [StashboxContainer.Resolver.cs](https://github.com/z4kn4fein/stashbox/blob/433c6721e718fda8bfcaaee6aad6de73a3015d9c/src/StashboxContainer.Resolver.cs#LL13C22-L13C22) there's a lot of copy-pasted code. I think this can be replaced with calls to other methods. In my opinion the readability and maintainability of the code in those two files is poor, and the code is very errorprone.

Also from what I understand all code inside `Resolve*` mathods in `StashboxContainer.Resolver.cs` can be replaced with a call to `rootScope.Resolve*`.

I like the concept of Microsoft's `IServiceProvider` interface, which is very simple. I think `IDependencyResolver` could be simplified and a lot of methods can be replaced with extension methods without huge perfromance penalty.

**Comment by z4kn4fein** [comment]
Hi @adambajguz,
That part of the code was initially introduced due to performance considerations. Originally, it was like you described, calling forward to methods on `rootScope`. The current version introduced measurable performance improvement by bypassing a method call on another interface. 

I don't see this improvement as a big deal now, and I agree it's not in good shape. There are more on the cons side. I have plans to clean that up sometime.

`IServiceProvider` describes a single really simple thing, but `IDependencyResolver` is also for a bit more complex than that. :) 
It already has extensions, I'm not sure yet whether it can be simplified, but I'll check on that too, and if so I'll move things to extension methods instead.

**Comment by z4kn4fein** [comment]
Hi @adambajguz, in [this](https://github.com/z4kn4fein/stashbox/commit/adf08ff76040736c30953e8146d3f15744db57d9) commit, I did some simplifications around those parts. I was actually able to move most of the `IDependencyResolver` methods to extensions. What do you think about the results?

**Comment by adambajguz** [comment]
Hi @z4kn4fein, now `IDependencyResolver` looks so much simpler - I like it! When do you plan to deploy new version?

**Comment by z4kn4fein** [comment]
@adambajguz Great! I've released it in `v5.11.0` along with the extensions `v5.3.0`.
