### ISSUE TITLE
injecting container itself?

### ISSUE THREAD

**Issue by bonesoul** [z4kn4fein/stashbox#38]
I'm migrating from simpleinjector and have a factory like below;

```
    public class CoreFactory: ICoreFactory
    {
        private readonly StashboxContainer _container;

        public CoreFactory(StashboxContainer container)
        {
            _container = container;
        }

        public IEngine GetEngine()
        {
            return _container.Resolve<IEngine>();
        }

        public ILogManager GetLogManager()
        {
            return _container.Resolve<ILogManager>();
        }
    }
```

registered with;

`            _container.RegisterSingleton<ICoreFactory, CoreFactory>();`

and resolving with;

`            var coreFactory = bootstrapper.Container.Resolve<ICoreFactory>(); // get core object factory.`

but couldnt get it working? is it possible to inject the container itself?

**Comment by z4kn4fein** [comment]
Hi @bonesoul 

Thank you for using Stashbox! The way you described is working only if you register the container into itself like: `_container.RegisterInstance(_container);`

If you only need to resolve some services inside your factory then there is a better way to get this working: 
You can change your `CoreFactory` to get an `IDependencyResolver` as a constructor parameter instead of a `StashboxContainer`. With this Stashbox automatically injects the actual resolution scope into your factory. So like this:

```
    public class CoreFactory: ICoreFactory
    {
        private readonly IDependencyResolver _container;

        public CoreFactory(IDependencyResolver container)
        {
            _container = container;
        }

        public IEngine GetEngine()
        {
            return _container.Resolve<IEngine>();
        }

        public ILogManager GetLogManager()
        {
            return _container.Resolve<ILogManager>();
        }
    }
```

Is this acceptable for you? Please share your thoughts, i also made some samples about these [here](https://github.com/z4kn4fein/stashbox/blob/master/src/stashbox.tests/IssueTests/38_Injecting_container_itself.cs).

**Comment by bonesoul** [comment]
great, it'll be more then enough for my usecase.
