### ISSUE TITLE
Singleton lifetime instances share dependencies

### ISSUE THREAD

**Issue by schuettecarsten** [z4kn4fein/stashbox#75]
I register several services with Singleton lifetime. That works so far. But all singletons share their dependencies. Is it possible to register a singleton service and tell Stashbox to use a dedicated, "isolated" scope for this service?

**Comment by z4kn4fein** [comment]
Yep, there are options to achieve that, you can mark your singletons as an "isolated" scope with the `DefinesScope()` option, then you can register their dependencies with Scoped lifetime, so the singletons will get their own instance from them.

Like:
```
class Singleton1
{
    public SingletonDep Dep { get; set; }    

    public Singleton1(SingletonDep dep) { this.Dep = dep;  }
}

class Singleton2
{
    public SingletonDep Dep { get; set; }

    public Singleton2(SingletonDep dep) { this.Dep = dep;  }
}


container.Register<Singleton1>(c => c.WithSingletonLifetime().DefinesScope())
    .Register<Singleton2>(c => c.WithSingletonLifetime().DefinesScope())
    .RegisterScoped<SingletonDep>();

var isSame = container.Resolve<Singleton1>().Dep != container.Resolve<Singleton2>().Dep; //false
```
So with this, you will get individual `SingletonDep` instances bound to the lifetime of your singletons.
Is this the thing you are searching for? 

Let me know if you have further questions or if this isn't what you need.

**Comment by schuettecarsten** [comment]
That looks good, but `DefinesScope()` needs a parameter in my version. Is `null` valid here?

**Comment by z4kn4fein** [comment]
Ah yeah, sorry, the parameterless option is only available in the prerelease version, it's not released yet, you can use a custom scope name with the stable version for now.

As I can see the problem could be that you are using the `RegisterTypes()` to register interface types, but the way it works is that it only accepts implementations and auto-discovers their implemented interfaces and base classes to register for. So it completely skips this configuration section, because the types you pass are all interfaces. 

The thing you want to achieve can be configured like this:
```
container.Register<IServiceLocator>(serviceLocator.GetType(), context => context
    .WithInstance(serviceLocator)
    .AsServiceAlso<IServiceProvider>()
    .ReplaceExisting()
    .WithoutDisposalTracking());
```
Just for the note, if the `IServiceProvider` you are using is from the `System` namespace it's automatically mapped to the container, you don't have to register it manually.

Sorry if the behavior caused confusion, maybe the docs should be clearer.

**Comment by schuettecarsten** [comment]
Even if I use your code, it does not work. My sample was reduced meta-code, here is the original one. The factory method is never called.

```
container.Register<IServiceLocator>(typeof(StashboxObjectProvider),
	context => context
		.WithFactory(delegate(IDependencyResolver resolver)
		{
			return new StashboxObjectProvider(container, resolver);
		})
		.AsServiceAlso<IObjectProviderRoot>()
		.AsServiceAlso<IObjectProvider>()
		.AsServiceAlso<IServiceProvider>()
		.ReplaceExisting()
		.WithoutDisposalTracking());
```

**Comment by z4kn4fein** [comment]
Ah I see, could you please send me the code of the `StashboxObjectProvider` and a class which shows the usage of it?
Thanks!

**Comment by z4kn4fein** [comment]
With which type are you referring to this registration? Are you referring to it with `IServiceProvider` as a dependency? The only thing I could think that the container chooses the current resolution scope as `IServiceProvider` instead of your implementation (because it implements `System.IServiceProvider`) and that is why your factory never called. If this is the case then I can make this feature configurable, but have you considered using the current scope as `IServiceProvider` dependency?

**Comment by schuettecarsten** [comment]
Just a quick info, this problem is still there with latest 3.1-preview.

**Comment by schuettecarsten** [comment]
I just tested around a bit. Even if I create new Scope and put instances into the scope like this, the scope does not resolve IObjectProvider correctly (returns null):

```
dependencyResolver = parentResolver
	.BeginScope()
	.PutInstanceInScope<IServiceLocator>(this, true)
	.PutInstanceInScope<IServiceProvider>(this, true)
	.PutInstanceInScope<IObjectProvider>(this, true)
	.PutInstanceInScope<IObjectProviderScope>(this, true);
```

**Comment by schuettecarsten** [comment]
I think I was able to figure out the root cause. I hope I can explain it correctly, as Stashbox ist somewhat complex here and it took some time to debug and understand what's going on.

The problem is here (ResolutionStrategy.cs, line 29++):

```
            if (resolutionContext.ResolutionScope.HasScopedInstances)
            {
                var scopedInstance = resolutionContext.ResolutionScope
                    .GetScopedInstanceOrDefault(typeInformation.Type, typeInformation.DependencyName);
                if (scopedInstance != null)
                    return resolutionContext.CurrentScopeParameter
                        .CallMethod(Constants.GetScopedInstanceMethod,
                            typeInformation.Type.AsConstant(),
                            typeInformation.DependencyName.AsConstant())
                        .ConvertTo(typeInformation.Type);
            }
```

The problem is that `resolutionContext.ResolutionScope` is the current scope that was used to resolve the service from Stashbox. But if the requested service has a singleton or named scope lifetime, then the singleton-/named scope must be used here, not the current scope.

**Comment by schuettecarsten** [comment]
This works with latest changes for #77, so I close this issue.
