### ISSUE TITLE
Please disable Lifetime validation by default

### ISSUE THREAD

**Issue by schuettecarsten** [z4kn4fein/stashbox#83]
Please disable Lifetime validation by default and add a method to "activate" it, like `WithLifetimeValidation()`. Usually, all features of Stashbox are activated using a ``With...` method, so please do so for lifetime validation.

**Comment by z4kn4fein** [comment]
Hey, 
Usually, it's working that way, however now I think it should be enabled by default because it's an important validation feature that could reveal lifetime misconfigurations. I'm trying to move that way where these kind of options are turned on by default. Like the circular dependency tracking, it's always turned on now and no way to disable it. Actually, there was no sense about leaving it disabled because the only thing you got was a stackoverflow when something was messed up.

**Comment by schuettecarsten** [comment]
I agree that lifetime validation is a very useful feature.

But sometimes, lifetimes cannot be configured correctly. Here is a small sample code, I only write the constructors here and the lifetimes that are used during service registration:

```
[Singleton]
public ProductResolver(ProductRepository repo)

[Scoped]
public ProductService(ProductRepository repo)

[Scoped]
public ProductRepository(DataContext context)

[Transient]
public DataContext(...)
```

In this case, it's correct that the ProductRepository is registered in Scoped scope, I want one repository per Scope. Also, the DataContext should be activated every time, meaning for each ProductRepository (and maybe lots of other repository classes in other scopes). The ProductService is also in Scoped lifetime.

But the ProductResolver is a singleton and registered in singleton scope - this is valid. The resolver class gets its own repository and data context class. Even if the repository and the context are registered scoped and transient, they should inherit the Singleton scope here (imho).

**Comment by schuettecarsten** [comment]
This brings me to another question. In the sample code above, if I register ProductResolver using `DefinesScope()`, how are the dependencies scoped resolved? In the scope that is implicitly created for the ProductResolver instance, or in the parent scope?

**Comment by z4kn4fein** [comment]
Yep, I know that there are cases when this validation fails but it's expected because the lifetime configuration is built consciously that way, this is why I added the option to turn it off. However, you are right and leave it disabled by default in the core project and turn it on wherever it's needed (in some extensions) might be a better approach. Also, I have to rethink the configuration mechanism, because when an extension turns a feature on by default, there is no easy way to disable.
